/*
 * Copyright (C) 2026 Navdeep Singh Sidhu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package in.co.s13.SIPS.executor;

import in.co.s13.SIPS.tools.Platform;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes the small launcher scripts that hand one task chunk to Ant.
 *
 * <p>These are generated at startup rather than shipped, so a node adapts to
 * whatever host it lands on. Previously the POSIX script was only written when
 * the OS was detected as Linux and every other platform — including macOS —
 * received a Windows batch file instead.
 */
public final class ExecutorScripts {

    private ExecutorScripts() {
    }

    public static String executorFileName(Platform platform) {
        requireSupported(platform);
        return platform == Platform.WINDOWS ? "process-executor.bat" : "process-executor.sh";
    }

    public static String simulateFileName(Platform platform) {
        requireSupported(platform);
        return platform == Platform.WINDOWS ? "simulate.bat" : "simulate.sh";
    }

    /**
     * Script that compiles and runs one chunk. Argument 1 is the chunk
     * directory, relative to the node's working directory.
     */
    public static String executorScript(Platform platform) {
        requireSupported(platform);
        if (platform == Platform.WINDOWS) {
            return """
                   @echo off
                   cd /d "%CD%\\%~1" || exit /b 1
                   call ant
                   """;
        }
        return """
               #!/bin/sh
               # Generated by SIPS at startup. Edits will be overwritten.
               set -e
               cd "$1"
               exec ant
               """;
    }

    /**
     * Script used by the simulation pass, which additionally forwards a value
     * to the build as {@code -Darg1}.
     */
    public static String simulateScript(Platform platform) {
        requireSupported(platform);
        if (platform == Platform.WINDOWS) {
            return """
                   @echo off
                   cd /d "%CD%\\%~1" || exit /b 1
                   call ant -Darg1=%~2
                   """;
        }
        return """
               #!/bin/sh
               # Generated by SIPS at startup. Edits will be overwritten.
               set -e
               cd "$1"
               exec ant -Darg1="$2"
               """;
    }

    /**
     * Writes both scripts into {@code binDir}, creating it if needed and
     * marking POSIX scripts executable.
     *
     * @throws IOException if the scripts cannot be written
     */
    public static void install(Platform platform, Path binDir) throws IOException {
        requireSupported(platform);
        Files.createDirectories(binDir);

        Path executor = binDir.resolve(executorFileName(platform));
        Path simulate = binDir.resolve(simulateFileName(platform));
        Files.writeString(executor, executorScript(platform));
        Files.writeString(simulate, simulateScript(platform));

        if (platform.isPosix()) {
            executor.toFile().setExecutable(true, false);
            simulate.toFile().setExecutable(true, false);
        }
    }

    private static void requireSupported(Platform platform) {
        if (platform == null || !platform.isSupported()) {
            throw new IllegalStateException(
                    "Cannot generate executor scripts for an unsupported platform: " + platform);
        }
    }
}
